### PR TITLE
23 mediator encounter endpoint

### PR DESCRIPTION
**Pull request by njogz**
# Description

Create an endpoint for handling encounters in the mediator

Closes medic/interoperability#23

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Review by samuelimoisili — APPROVED** [review]

**Comment by andrablaj** [comment]
@njogz I tried the LTFU flow by using this branch, and when I submitted the task, I got the following error in the sentinel log:

> 2023-03-29 11:49:05 ERROR: Failed to push f957f3a7-716a-4fe7-b7bf-c4dab15da839 to FHIR_encounter: Error: connect ECONNREFUSED 127.0.0.1:5001  

Is there extra configuration needed for the encounter creation?

**Comment by andrablaj** [comment]
Yes, I use the same credentials to login into the CHT.

**Comment by andrablaj** [comment]
If I access the follow-up flow via `https://*****/contacts/patientUUID/report/interop_follow_up`, I can see the encounter being submitted correctly. 

Screenshot 2023-03-30 at 16 27 19

It's really the `service-request` that seems problematic. I will try the LTFU flow with the `main` branch.

**Comment by andrablaj** [comment]
OK, I managed to reproduce the problem with the `main` branch, so this does not seem connected to this PR. `service-request` is failing with `unable to create the follow up task` error.

Screenshot 2023-03-30 at 16 34 33

You can merge this PR, as the encounter endpoint works correctly. Can you open another issue to investigate why the task creation is suddenly broken?

**Comment by andrablaj** [comment]
@njogz I found [the problem](https://github.com/medic/interoperability/issues/59), it was introduced with a previous PR. I managed to fix the main branch, I will open a PR shortly

**Comment by andrablaj** [comment]
@njogz I believe that with [that fix,](https://github.com/medic/interoperability/issues/59) the flow should be back to normal. Can you please bring merge the `main` to this and let's try to test again?

**Pull request merged**
